# services:
#   postgres:
#     image: "postgres:17-alpine"
#     container_name: ecommerce-postgres
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: secret
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 30s
#     restart: unless-stopped

#   redis:
#     image: "redis:7-alpine"
#     container_name: ecommerce-redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#       start_period: 10s
#     restart: unless-stopped

# volumes:
#   postgres_data:
#     driver: local
#   redis_data:
#     driver: local
